nnmon/urls.py
from django.conf.urls import patterns, include, url
from django.views.generic import TemplateView, RedirectView
from django.conf import settings
from django.contrib import admin
from bt import views as bt
from bt.feeds import RssSiteNewsFeed, AtomSiteNewsFeed

from bt.api import APIResource, OperatorResource

api_resource = APIResource()
operator_api_resource = OperatorResource()

admin.autodiscover()

urlpatterns = patterns('',
    url(r'^$',
        view=bt.AddForm.as_view(),
        name="homepage"),
    url(r'^list/$',
        view=bt.ViolationsList.as_view(),
        name="list_violations"),
    url(r'^list/(?P<country>\w+)/$',
        view=bt.ViolationsList.as_view(),
        name="filter_country"),
    url(r'^list/(?P<country>\w+)/(?P<operator>\w+)/$',
        view=bt.ViolationsList.as_view(),
        name="filter_operator"),
    # violation cannonical url and redirections
    url(r'^(?P<id>[0-9]*)$',
        RedirectView.as_view(url='/view/%(id)s')),
    url(r'^view/(?P<id>[0-9]*)$',
        view=bt.ViolationView.as_view(),
        name="violation_url"),
    url(r'^attach/(?P<id>[0-9]*)$',
        view=bt.get_attach,
        name="attach"),
    # different data outputs
    url(r'^csv$',
        view=bt.ascsv,
        name="csv_output"),
    url(r'^ods$',
        view=bt.asods,
        name="ods_output"),
    url(r'^rss/$',
        view=RssSiteNewsFeed(),
        name="rss_output"),
    url(r'^atom/$',
        view=AtomSiteNewsFeed(),
        name="atom_output"),
    url(r'^activate/$',
        view=bt.activate,
        name="activate"),
    url(r'^confirm/(?P<id>[0-9a-z]*)$',
        view=bt.confirm,
        name="confirm"),
    url(r'^confirm/(?P<id>[0-9]*)/(?P<name>.*)$',
        view=bt.confirm,
        name="confirm_full"),
    url(r'^moderate/$',
        view=bt.moderate,
        name="moderate"),
    url(r'^lookup/',
        view=bt.LookupView.as_view(template_name='search/lookup.json'),
        name="lookup"),
    url(r'^accounts/logout$',
        'django.contrib.auth.views.logout', {'next_page': '/'}),
    url(r'^accounts/',
        include('registration.urls')),
    url(r'^comments/',
        include('django_comments.urls')),
    url(r'^about/$',
        TemplateView.as_view(template_name='nn.html')),
    url(r'^start/$',
        TemplateView.as_view(template_name='start.html')),
    url(r'^captcha/',
        include('captcha.urls')),
    url(r'^admin/',
        include(admin.site.urls)),
    url(r'^api/',
        include(api_resource.urls)),
    url(r'^api/',
        include(operator_api_resource.urls)),
    url(r'^search/',
        bt.ViolationSearchView.as_view(template_name='search/search.html')),
)

if settings.DEV_SERVER == True:
    urlpatterns += patterns('',
        (r'^site_media/(?P<path>.*)$',
            'django.views.static.serve',
            {'document_root': settings.MEDIA_PATH}),
    )

bt/models.py
from django.db import models
from django.utils.translation import ugettext_lazy as _
from django_comments.moderation import CommentModerator, moderator

COUNTRIES = (
    ('BE', _('Belgium')),
    ('BG', _('Bulgaria')),
    ('CH', _('Switzerland')),
    ('CZ', _('Czech Republic')),
    ('DK', _('Denmark')),
    ('DE', _('Germany')),
    ('EE', _('Estonia')),
    ('IE', _('Ireland')),
    ('EL', _('Greece')),
    ('ES', _('Spain')),
    ('FR', _('France')),
    ('IC', _('Iceland')),
    ('IS', _('Iceland')),
    ('IT', _('Italy')),
    ('CY', _('Cyprus')),
    ('LI', _('Liechtenstein')),
    ('LV', _('Latvia')),
    ('LT', _('Lithuania')),
    ('LU', _('Luxembourg')),
    ('HU', _('Hungary')),
    ('MT', _('Malta')),
    ('NL', _('Netherlands')),
    ('NO', _('Norway')),
    ('AT', _('Austria')),
    ('PL', _('Poland')),
    ('PT', _('Portugal')),
    ('RO', _('Romania')),
    ('SI', _('Slovenia')),
    ('SK', _('Slovakia')),
    ('FI', _('Finland')),
    ('SE', _('Sweden')),
    ('UK', _('United Kingdom')),
    )
RESOURCES = (
    ('other', _('other')),
    ('port', _('port')),
    ('protocol', _('protocol')),
    ('service', _('service')),
    ('site', _('website')),
    ('user', _('user')),
    ('ip', _('ip')),
    ('video', _('video streaming')),
    ('audio', _('audio streaming')),
    ('class', _('class of application or contraint')),
    )
TYPES = (
    ('zerorating', _('Zero Rating')),
    ('specialised', _('Specialised Service')),
    ('blocking', _('Blocking')),
    ('throttling', _('Throttling')),
    ('prioritisation', _('Prioritisation')),
    ('other', _('Other'))
    )
MEDIA = (
    ('fixed', _('Fixed')),
    ('mobile', _('Mobile')),
    )
STATUS = (
    ('moreinfo', _('Need more info')),
    ('new', _('New')),
    ('verified', _('Verified')),
    ('duplicate', _('Duplicate')),
    ('ooscope', _('Out of scope')),
    ('closed', _('Closed')),
    )

class Operator(models.Model):
    """
    Define the concept of an internet provider/network operator
    """
    name = models.CharField(max_length=256)
    logo = models.ImageField(upload_to='operator_logo', null=True, blank=True)

    def reported_violations(self):
        return self.violations.count()
    reported_violations.short_description = 'Reported Violations'

    def __unicode__(self):
        return self.name

class Violation(models.Model):
    country = models.CharField(max_length=2, choices=COUNTRIES)
    operator_ref = models.ForeignKey(Operator, related_name="violations")
    contract = models.CharField(max_length=256, blank=True)
    resource = models.CharField(max_length=20, choices=RESOURCES, blank=True)
    resource_name = models.CharField(max_length=4096, blank=True)
    type = models.CharField(max_length=20, choices=TYPES, blank=True)
    media = models.CharField( max_length=20, choices=MEDIA, blank=True)
    temporary = models.BooleanField( )
    contractual = models.BooleanField()
    contract_excerpt = models.TextField(null=True, blank=True)
    loophole = models.BooleanField()
    activationid= models.CharField(max_length=128, null=True, blank=True)
    state = models.CharField(max_length=20, choices=STATUS, default='new', blank=True)
    editorial = models.TextField(null=True, blank=True)
    old = models.BooleanField(default="False")
    creation_date = models.DateField(auto_now_add=True)

    def confirmations(self):
        return self.confirmation_set.filter(key='').count()

    class Admin:
        pass

    @property
    def operator(self):
        return self.operator_ref.name

    @models.permalink
    def get_absolute_url(self):
        return ('violation_url', (), 
            {'id': self.pk })

    def __unicode__(self):
        return "#%s %s/%s" % (self.pk, self.country, self.operator)

class Comment(models.Model):
    submitter_email = models.EmailField()
    submitter_name = models.CharField(max_length=20)
    consent = models.BooleanField( )
    comment = models.TextField()
    timestamp = models.DateTimeField()
    violation = models.ForeignKey(Violation)

    class Admin:
        pass

    def __unicode__(self):
        return _("Comment #%s") % (self.pk)

class Attachment(models.Model):
    storage = models.FileField(upload_to='static')
    name= models.CharField(max_length=512)
    type= models.CharField(max_length=512)
    comment = models.ForeignKey(Comment)

    class Admin:
        pass

    def __unicode__(self):
        return self.name

class Confirmation(models.Model):
    key=models.CharField(max_length=64, blank=True)
    email=models.EmailField()
    violation = models.ForeignKey(Violation)

    class Admin:
        pass

class ViolationModerator(CommentModerator):
    email_notification = True
    moderate_after        = 0
    def moderate(self, comment, content_object, request):
        return True

if Violation not in moderator._registry:
    moderator.register(Violation, ViolationModerator)

class FeaturedCase(models.Model):
    case = models.OneToOneField(Violation)

    class Admin:
        pass

    def __unicode__(self):
        return u"*%s*" % self.case

bt/forms.py
from django import forms
from django.conf import settings
from django.utils.translation import ugettext_lazy as _
from haystack.forms import SearchForm
from haystack.query import SearchQuerySet
from bt.models import Violation, COUNTRIES, RESOURCES, TYPES, MEDIA
from bt.multifile import MultiFileField
from operator import itemgetter
from captcha.fields import CaptchaField

class AdvancedEditor(forms.Textarea):
    class Media:
        js = (settings.MEDIA_URL+'/js/tinymce/tiny_mce.js',)

        def __init__(self, language=None, attrs=None):
            self.language = language or settings.LANGUAGE_CODE[:2]
            self.attrs = {'class': 'advancededitor'}
            if attrs: self.attrs.update(attrs)
            super(AdvancedEditor, self).__init__(attrs)

class AddViolation(forms.Form):
    resource_name = forms.CharField(required=True, max_length=4096, label=_('Please describe the discrimination'), help_text=_("What service or site, or person is unavailable or seems artificially slowed down. e.g. VoIP, p2p, filesharing, specific websites, etc."))
    country = forms.ChoiceField(required=True, choices=(('',''),)+tuple(sorted(COUNTRIES,key=itemgetter(1))), label=_("Country"), help_text=_('EU member state where the discrimination is reported.'))
    operator = forms.CharField(required=True, max_length=256, label=_("Operator"), help_text=_('The ISP or operator providing the Internet service.'))
    contract = forms.CharField(required=True, max_length=256, label=_("Contract"), help_text=_('The specific contract at the ISP provider. (please be as specific as possible)'))
    media = forms.ChoiceField(required=True, choices=tuple(sorted(MEDIA,key=itemgetter(1))), label=_('Is the Internet connection over mobile or fixed line?'))
    comment = forms.CharField(required=True, widget=AdvancedEditor(), label=_('Please describe the symptoms you are experiencing.'))
    email = forms.EmailField(required=True, label=_('Email (set this to enable saving)'), help_text=_("We need your email to validate your report. Your email address is obligatory, but we will never use your personal data for anything else than checking the submission. (see next for an optional exception)"))
    consent = forms.BooleanField(required=False, label=_("I want to help further"), help_text=_("We need your consent to contact you for clarifications regarding your report. This is optional, but helps us improve the quality of the reports. Thanks!"))
    nick = forms.CharField(required=False, label=_("Name or nickname"), help_text=_("We need some name to display that instead of an email address."))
    attachments = MultiFileField(required=False, label=_("Attach screenshot, document or any other relevant information."))
    resource = forms.ChoiceField(required=False, choices=RESOURCES, label=_('What is the affected resource type. (optional)'))
    temporary = forms.BooleanField(required=False, label=_('Is the discrimination only temporary, e.g. due to network overload? (optional)'))
    loophole = forms.BooleanField(required=False, label=_('Is there another offer provided by this Operator which removes this discrimination? (optional)'))
    contractual = forms.BooleanField(required=False, label=_('The discrimination is described in the subscribers contract.'))
    contract_excerpt = forms.CharField(required=False, widget=AdvancedEditor(), label=_('Please copy the relevant section describing the discrimination from the user contract. (optional)'))
    type = forms.ChoiceField(required=True, choices=tuple(TYPES), label=_('How would you describe the discrimination?'))
    captcha = CaptchaField(label=_("In order to protect against spam, please fill in the result of the following calculation. (note the + and the * are somewhat confusing)"))

class SearchViolation(SearchForm):
    country = forms.ChoiceField(required=False, choices=(('',''),)+tuple(sorted(COUNTRIES,key=itemgetter(1))), label=_("Country"), help_text=_('EU member state where the discrimination is reported.'))
    operator = forms.CharField(required=False, max_length=256, label=_("Operator"), help_text=_('The ISP or operator providing the Internet service.'))
    contract = forms.CharField(required=False, max_length=256, label=_("Contract"), help_text=_('The specific contract at the ISP provider. (please be as specific as possible)'))
    media = forms.ChoiceField(required=False, choices=(('',''),)+tuple(sorted(MEDIA,key=itemgetter(1))), label=_('Is the Internet connection over mobile or fixed line?'))

    def search(self):
        # By default, the search field is q. So let's check if it's empty
        if not self.cleaned_data['q']:
            sqs = SearchQuerySet().all().exclude(old=True)
        else:
            sqs = super(SearchViolation, self).search().exclude(old=True)

        if not self.is_valid():
            return self.no_query_found()

        if self.cleaned_data['operator']:
            sqs = sqs.filter(operator__icontains=self.cleaned_data['operator'])

        if self.cleaned_data['contract']:
            sqs = sqs.filter(contract__icontains=self.cleaned_data['contract'])

        if self.cleaned_data['media']:
            sqs = sqs.filter(media=self.cleaned_data['media'])

        if self.cleaned_data['country']:
            sqs = sqs.filter(country=self.cleaned_data['country'])

        return sqs

class QuickSearchViolation(forms.Form):
    query = forms.CharField(required='True', max_length=256, label=_("Search"), help_text=_('Search for an existing violation'))

nnmon/templates/feeditem.html
{% load bt %}
{% load i18n %}
{%if obj.comment_set.all.0%}
 <h3>{%trans "Description" %}</h3>
 <div class="description-node">
   <div class="description">{{obj.comment_set.all.0.comment|safe}}</div>
   <span class="submitter">Submitter: {%if obj.comment_set.all.0.submitter_name%}{{obj.comment_set.all.0.submitter_name}}{%else%}{{obj.comment_set.all.0.submitter_email}}{%endif%}</span> - <span class="comment_date">{{obj.comment_set.all.0.timestamp|date:"SHORT_DATE_FORMAT" }}</span>
   {%if obj.comment_set.all.0.attachment_set.all%}
   <div class="attachs">
      {% trans "Attachments" %}
     <ul>
       {%for a in obj.comment_set.all.0.attachment_set.all%}
       <li><a href="{{a.storage.url}}">{{a.storage.name}}</a></li>
       {%endfor%}
     </ul>
   </div>
   {%endif%}
 </div>
{%endif%}
<ul>
{%if obj.media%}<li>{% trans "Media" %}: {{obj.media}}</li>{%endif%}
{%if obj.resource_name%}<li>{% trans "Affected Resource/service" %}: {{obj.resource_name}}</li>{%endif%}
{%if obj.type%}<li>{% trans "Type" %}: {{obj.type}}</li>{%endif%}
{%if obj.temporary%}<li>{% trans "Temporary restriction" %}: {% trans "yes" %}</li>{%endif%}
{%if obj.loophole%}<li>{% trans "Loophole offering" %}: {% trans yes %}}</li>{%endif%}
{%if obj.contractual%}<li>{% trans "Contractual restriction" %}: {% trans "yes" %}</li>{%endif%}
</ul>
{%if obj.contract_excerpt%}{% trans "Contract excerpt" %}: {{obj.contract_excerpt|safe}}{%endif%}

nnmon/templates/index.html
{% extends "base.html" %}
{% load bt %}
{% load i18n %}
{% load bootstrap3 %}
{% block active_tab_home %}class="active"{% endblock %}
{% block styles %}
<link rel="stylesheet" type="text/css" media="all" href="/static/css/jquery-ui.css" />
{% endblock %}

{% block scripts %}
<script type="text/javascript">
$('.metoo').submit(function(event) {
	event.preventDefault();
	var form = $(this);
	var pk = $(form).attr("id")
	var email = $(form).find("#email-" + pk).val();

	$.ajax({
		url: "/confirm/" + pk + "/" + email,
		success: function(data) {
			form.find("div").html(data);
		}
	});
});
$("#lookup_btn").click(function(event) {
	event.preventDefault();
	$.ajax({
		dataType: "json",
		url: "/lookup/",
		data: {
			country: $("#id_country").val(),
			operator: $("#id_operator").val(),
			contract: $("#id_contract").val(),
			media: $("#id_media").val(),
			type: $("#id_type").val(),
		},
		success: function(data) {
			var filtered = data.filter(function(data) {
				return data.fields.state in ["ooscope", "duplicate"]
			});
			if (filtered.length == 0) {
				$("#lookup_btn").parent().parent().hide();
				$("#collapseField").collapse('show');
				return;
			}

			filtered = filtered.slice(0, 10);
			$.each(filtered, function(key, obj) {
				if (obj.fields.state in ["ooscope", "duplicate"]) {
					return;
				};
				$("#modal-list").append(
						"<dt>" + obj.fields.resource + "</dt>" +
						"<dd><p>" + obj.fields.editorial + "</p>" +
						"<div class=\"confirm\"><a class=\"btn btn-default\">{% trans "Me too!" %}</a>" +
						"<div class=\"info-validate float-confirm\">" +
						"<form method=\"get\" action=\"\" id=\"i" + obj.pk + "\" class=\"confirm_form\">" +
						"<div>" +
						"<label>{% trans "In order to <strong>confirm</strong> this report, please enter your email address" %}</label>" +
						"<input type=\"text\" name=\"email\" />" +
						"<input type=\"hidden\" value=\"{{obj.pk}}\" />" +
						"<input type=\"submit\" value=\"{% trans "Ok" %}\" />" +
						"</div>" +
						"</form>" +
						"</div>" +
						"</dd>"
						);
			});
			$('#similar_modal').modal('show');
			console.log("Modal displayed");
		},
		error: function(xhr, status, err) {
			console.log(err, xhr);
		}
	});
});

$("#btn_dismiss").click(function(event) {
	event.preventDefault();
	$("#similar_modal").modal('hide');
	$("#lookup_btn").parent().parent().hide();
	$("#collapseField").collapse('show');
});
</script>
{% endblock %}

{%block content%}
<div class="row">
	<div class="col-xs-12 col-md-8" id="content">
		<h2>{% trans "On the Internet, <strong>you</strong> decide what you do, right? <i>Maybe not!</i>" %}</h2>
		<p>{% trans "Telecommunication providers and Internet companies are trying to control what you do online. They want to block and throttle some of your communications, and charge you to use certain online services, content or applications. The main aim of RespectMyNet is to bring attention to these Net Neutrality violations and demand that regulators take action to stop this. " %}</p>
		<p>{% trans "The EU law recently adopted on Net Neutrality is ambiguous and the telecom regulators have the job of deciding how it should be implemented." %}
		<p>{% trans "You can help. You can report Net Neutrality violations and help the regulators protect the open Internet in Europe!" %}</p>
		<p>{% trans "Help us keep track of all the ways that Internet providers are violating our online freedoms. Tell us about how your landline or mobile Internet operator restricts your Internet connection. It will take less than two minutes!" %}</p>
		<p>{% trans "Don't hesitate to give us feedback on this application by reporting any idea or issue with RespectMyNet.eu here: <a href='https://nnmon.quadpad.lqdn.fr/feedback'>Feedback pad page</a>" %}</p>
		<h2 id="stats-title">{% trans "Statistics" %}</h2>
		<div id="stats_graph" ></div>
		<ul id="stats">
			{% for t, n in stats %}
			<li class="stat">
				<dl>
					<dt class="inline">{{t}}</dt>
					<dd class="inline"><strong>{{n}}</strong></dd>
				</dl>
			</li>
			{% endfor %}
		</ul>
		<h2 id="featured-title">{% trans "Featured Cases" %}</h2>
		<table class="table table-stripped" id="featured_cases">
			<thead>
				<tr>
					<th style="width: 70%;">{% trans "Infringing offering" %}</th>
					<th>{% trans "Confirmed" %}</th>
					<th></th>
				</tr>
			</thead>
			<tbody>
				{% for violation in violations %}
				<tr>
					<td><a href="{{ violation.get_absolute_url }}">{{ violation.operator }} ({{ violation.country|country }}) {{ violation.contract }}</a>
						<div class="well collapse" id="info-{{ violation.pk }}">
							<form method="post" class="metoo" action="/confirm/{{ violation.pk }}" id="{{ violation.pk }}">
								<div class="form-group form-inline">
									<label for"email-{{ violation.pk }}">{% trans "In order to <strong>confirm</strong> this report, please enter your email address" %}</label>
									{% csrf_token %}
									<input type="email" id="email-{{ violation.pk }}" class="form-control" name="email" placeholder="Email"/>
									<input type="hidden" id="id-{{ violation.pk }}" value="{{ violation.pk }}" />
									<div class="btn-group" role="group" aria-label="confirm-deny">
										<button class="btn btn-success">{% trans "OK" %}</ button>
											<button data-toggle="collapse" data-target="#info-{{ violation.pk}}" aria-expanded="false" aria-controls="info-{{ volation.pk }}" type="button" class="btn btn-danger" >{% trans "Cancel" %}</button>
									</div>
								</div>
							</form>
						</div>
					</td>
					<td class='align-right'>{{ violation.confirmations }}</td>
					<td class='align-right'><button type="button" class="btn btn-default" data-toggle="collapse" data-target="#info-{{ violation.pk}}" aria-expanded="false" aria-controls="info-{{ volation.pk }}">{% trans "Me too!" %}</button>
					</td>
				</tr>
				<tr>
					<td colspan="3">
						<div id="description" class='round-box'>
							<strong>{% trans "Affected Resource" %}:</strong> {{violation.resource_name}}
							{%for c in violation.comment_set.all%}
							<div class="description">{{c.comment|safe}}</div>
							<span class="submitter">{%if c.submitter_name%}{{c.submitter_name}}{%else%}{{c.submitter_email}}{%endif%}</span> - <span class="comment_date">{{c.timestamp|date:"SHORT_DATE_FORMAT" }}</span>
						</div>
						{%endfor%}
					</td>
				</tr>
				{% endfor %}
			</tbody>
		</table>
	</div>
	<div id="add-case" class="col-xs-12 col-md-4">
		<div class="panel panel-info">
			<div class="panel-heading">
				<h2>{% trans "Add New Case" %}</h2>
			</div>
			<div class="panel-body">
				{% if forms.error %}
				{% for field in form %}
				{% for error in field.error %}
				<div class="alert alert-error">
					{{ error|escape }}
				</div>
				{% endfor %}
				{% endfor %}
				{% endif %}
				<p>{% trans "Please report cases of zero-rating (services which are excluded from your download limit), specialised services or the blocking, throttling or prioritisation of online services. For a more detailed description of what to report, check our <a href='/about/#guidelines'>guidelines</a>." %}
				<form name="addForm" enctype="multipart/form-data" action="/" method="post" class="form">
					{% csrf_token %}
					{% bootstrap_field form.country %}
					{% bootstrap_field form.operator %}
					{% bootstrap_field form.contract %}
					{% bootstrap_field form.media %}
					{% bootstrap_field form.type %}
					<div class="collapse" id="collapseField">
						<hr />
						{% bootstrap_field form.temporary %}
						{% bootstrap_field form.loophole %}
						{% bootstrap_field form.contractual %}
						{% bootstrap_field form.resource_name %}
						{% bootstrap_field form.resource %}
						{% bootstrap_field form.contract_excerpt %}
						{% bootstrap_field form.attachments %}
						{% bootstrap_field form.comment %}
						<hr />
						{% bootstrap_field form.consent %}
						{% bootstrap_field form.email %}
						{% bootstrap_field form.nick %}
						{% bootstrap_field form.captcha %}
						{% buttons %}
						<button type="submit" class="btn btn-primary">{% trans "save" %}</button>
						{% endbuttons %}
					</div>
				</form>
			</div>
			<div class="panel-footer">
				{% buttons %}
				<button id="lookup_btn" class="btn btn-default" type="button">{% trans "Continue" %}</button>
				{% endbuttons %}
			</div>
		</div>
	</div>
</div>
<div class="modal fade" id="similar_modal" tabindex="-1" role="dialog" aria-labelledby="SimilarModalLabel">
	<div class="modal-dialog">
		<div class="modal-content">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
				<h4 class="modal-title" id="SimilarModalLabel">{% trans "Similar cases" %}</h4>
			</div>
			<div class="modal-body">
				<p>{% trans "Those are cases that might be similar to yours, please feel free to add your input on those cases instead of adding yours if they overlap." %}</p>
				<dl id="modal-list">
				</dl>
				</table>
			</div>
			<div class="modal-footer">
				<button type="button" id="btn_dismiss" class="btn btn-default" data-dismiss="modal">{% trans "Dismiss" %}</button>
			</div>
		</div>
	</div>
</div>
{%endblock%}